CREATE TABLE IF NOT EXISTS "agency" (
  "id" TEXT,
  "IsDeleted" TEXT,
  "MasterRecordId" TEXT,
  "Name" TEXT,
  "Type" TEXT,
  "ParentId" TEXT,
  "BillingStreet" TEXT,
  "BillingCity" TEXT,
  "BillingState" TEXT,
  "BillingPostalCode" TEXT,
  "BillingCountry" TEXT,
  "BillingLatitude" TEXT,
  "BillingLongitude" TEXT,
  "BillingGeocodeAccuracy" TEXT,
  "BillingAddress" TEXT,
  "ShippingStreet" TEXT,
  "ShippingCity" TEXT,
  "ShippingState" TEXT,
  "ShippingPostalCode" TEXT,
  "ShippingCountry" TEXT,
  "ShippingLatitude" TEXT,
  "ShippingLongitude" TEXT,
  "ShippingGeocodeAccuracy" TEXT,
  "ShippingAddress" TEXT,
  "Phone" TEXT,
  "Website" TEXT,
  "PhotoUrl" TEXT,
  "Industry" TEXT,
  "NumberOfEmployees" TEXT,
  "Description" TEXT,
  "OwnerId" TEXT,
  "CreatedDate" TEXT,
  "CreatedById" TEXT,
  "LastModifiedDate" TEXT,
  "LastModifiedById" TEXT,
  "SystemModstamp" TEXT,
  "LastActivityDate" TEXT,
  "LastViewedDate" TEXT,
  "LastReferencedDate" TEXT,
  "IsCustomerPortal" TEXT,
  "Jigsaw" TEXT,
  "JigsawCompanyId" TEXT,
  "AccountSource" TEXT,
  "SicDesc" TEXT,
  "Agency_Contact_Email__c" TEXT,
  "Agency_Contact_Fax__c" TEXT,
  "Agency_Contact_Name__c" TEXT,
  "Agency_Contact_Phone__c" TEXT,
  "Agency_Contact_Primary_Phone__c" TEXT,
  "Agency_Contact_Secondary_Phone__c" TEXT,
  "Agency_Contact_Title__c" TEXT,
  "Email__c" TEXT,
  "Employee_Identification_EIN__c" TEXT,
  "Fax__c" TEXT,
  "Legal_Status_Other__c" TEXT,
  "Legal_Status__c" TEXT,
  "Mission_Statement__c" TEXT,
  "Person_in_Charge_Email__c" TEXT,
  "Person_in_Charge_Fax__c" TEXT,
  "Person_in_Charge_Name__c" TEXT,
  "Person_in_Charge_Primary_Phone__c" TEXT,
  "Person_in_Charge_Secondary_Phone__c" TEXT,
  "Person_in_Charge_Title__c" TEXT,
  "Status__c" TEXT,
  "AKA_Name__c" TEXT,
  "Admin_Hours__c" TEXT,
  "Administrator_Extension__c" TEXT,
  "Agency_Accessibility__c" TEXT,
  "Agency_Key__c" TEXT,
  "Agency_Phone_10__c" TEXT,
  "Agency_Phone_1__c" TEXT,
  "Agency_Phone_2__c" TEXT,
  "Agency_Phone_3__c" TEXT,
  "Agency_Phone_4__c" TEXT,
  "Agency_Phone_5__c" TEXT,
  "Agency_Phone_6__c" TEXT,
  "Agency_Phone_7__c" TEXT,
  "Agency_Phone_8__c" TEXT,
  "Agency_Phone_9__c" TEXT,
  "Agency_Phones__c" TEXT,
  "Agency_Type__c" TEXT,
  "Billing_Address_is_Confidential__c" TEXT,
  "Building__c" TEXT,
  "Contact_1_Email__c" TEXT,
  "Contact_1_Extension__c" TEXT,
  "Contact_1_Name__c" TEXT,
  "Contact_1_Phone__c" TEXT,
  "Contact_1_Title__c" TEXT,
  "Contact_2_Email__c" TEXT,
  "Contact_2_Extension__c" TEXT,
  "Contact_2_Name__c" TEXT,
  "Contact_2_Phone__c" TEXT,
  "Contact_2_Title__c" TEXT,
  "Contact_3_Email__c" TEXT,
  "Contact_3_Extension__c" TEXT,
  "Contact_3_Name__c" TEXT,
  "Contact_3_Phone__c" TEXT,
  "Contact_3_Title__c" TEXT,
  "County__c" TEXT,
  "Created_By_Legacy__c" TEXT,
  "Created_Date_Legacy__c" TEXT,
  "EB_Send__c" TEXT,
  "Facility_Type__c" TEXT,
  "Formal_Update_Date_Legacy__c" TEXT,
  "IRS_Status__c" TEXT,
  "Inactivated_Date__c" TEXT,
  "Local_Location__c" TEXT,
  "Location_ID__c" TEXT,
  "Mailing_Address_is_Confidential__c" TEXT,
  "Mailing_County__c" TEXT,
  "Not_in_Directory__c" TEXT,
  "Not_in_Website__c" TEXT,
  "Overview__c" TEXT,
  "Public_Transit_Access__c" TEXT,
  "Reason_for_Inactivation__c" TEXT,
  "Staff_Assigned__c" TEXT,
  "Survey_Password__c" TEXT,
  "Tax_ID__c" TEXT,
  "Unpublished__c" TEXT,
  "Update_Date_Legacy__c" TEXT,
  "Updated_By_Legacy__c" TEXT,
  "Year_Incorporated__c" TEXT,
  "Disaster_Preparedness_Services__c" TEXT,
  "Suite__c" TEXT,
  "Formal_Update_Date__c" TEXT,
  "Days_Since_Last_Update__c" TEXT,
  "Days_Since_Last_Formal_Update__c" TEXT,
  "attributes" TEXT,
  "Agency_Accessibility_Other__c" TEXT,
  "Contact_1_Secondary_Phone__c" TEXT,
  "Contact_2_Secondary_Phone__c" TEXT,
  "Contact_3_Secondary_Phone__c" TEXT,
  "How_long_has_Agency_Serviced_in_Hawaii__c" TEXT,
  "How_long_has_agency_had_legal_status__c" TEXT,
  "IRS_Status_Other__c" TEXT,
  "Mailing_Building__c" TEXT,
  "Mailing_Suite__c" TEXT,
  "Any_Disaster_Preparedness_Services__c" TEXT,
  "Describe_Disaster_Preparedness_Services__c" TEXT,
  "Mailing_Address_Same_as_Physical__c" TEXT,
  "Partner_Agency__c" text,
  "Partners_In_Care_PIC_Partner_Agency__c" text,
  "Internal_Updates_Only__c" text
);

CREATE TABLE IF NOT EXISTS "program" (
  "id" TEXT,
  "OwnerId" TEXT,
  "IsDeleted" TEXT,
  "Name" TEXT,
  "CreatedDate" TEXT,
  "CreatedById" TEXT,
  "LastModifiedDate" TEXT,
  "LastModifiedById" TEXT,
  "SystemModstamp" TEXT,
  "LastActivityDate" TEXT,
  "LastViewedDate" TEXT,
  "LastReferencedDate" TEXT,
  "Additional_Program_Information__c" TEXT,
  "Age_Range_restrictions__c" TEXT,
  "Criteria_for_Participation__c" TEXT,
  "Description__c" TEXT,
  "Family_Composition_restrictions__c" TEXT,
  "Fees_Other__c" TEXT,
  "Fees__c" TEXT,
  "Gender_restrictions_Other__c" TEXT,
  "Income_Status_restrictions__c" TEXT,
  "Insurance_Other__c" TEXT,
  "Medical_Insurance_Plans_Accepted__c" TEXT,
  "Other_restrictions__c" TEXT,
  "Program_Contact_Email__c" TEXT,
  "Program_Contact_Fax__c" TEXT,
  "Program_Contact_Name__c" TEXT,
  "Program_Contact_Phone__c" TEXT,
  "Program_Contact_Title__c" TEXT,
  "Race_or_Ethnicity_restrictions__c" TEXT,
  "Status__c" TEXT,
  "of_Sites__c" TEXT,
  "AKA_Name__c" TEXT,
  "Accessibility__c" TEXT,
  "Account__c" TEXT,
  "Additional_Information__c" TEXT,
  "Additional_Phones__c" TEXT,
  "Eligibility__c" TEXT,
  "Fax__c" TEXT,
  "Fees_Text__c" TEXT,
  "Group_Contact_10__c" TEXT,
  "Group_Contact_1__c" TEXT,
  "Group_Contact_2__c" TEXT,
  "Group_Contact_3__c" TEXT,
  "Group_Contact_4__c" TEXT,
  "Group_Contact_5__c" TEXT,
  "Group_Contact_6__c" TEXT,
  "Group_Contact_7__c" TEXT,
  "Group_Contact_8__c" TEXT,
  "Group_Contact_9__c" TEXT,
  "Hours__c" TEXT,
  "Insurance__c" TEXT,
  "Intake_Person__c" TEXT,
  "Intake_Procedure__c" TEXT,
  "Languages_Text__c" TEXT,
  "Languages__c" TEXT,
  "Legacy_Service_Area__c" TEXT,
  "Location_ID__c" TEXT,
  "Program_Email_Text__c" TEXT,
  "Program_Email__c" TEXT,
  "Program_Phone__c" TEXT,
  "Program_Taxonomies__c" TEXT,
  "ServiceArea__c" TEXT,
  "Service_Description__c" TEXT,
  "Service_Group__c" TEXT,
  "Service_ID__c" TEXT,
  "Target__c" TEXT,
  "Taxonomy_10__c" TEXT,
  "Taxonomy_1__c" TEXT,
  "Taxonomy_2__c" TEXT,
  "Taxonomy_3__c" TEXT,
  "Taxonomy_4__c" TEXT,
  "Taxonomy_5__c" TEXT,
  "Taxonomy_6__c" TEXT,
  "Taxonomy_7__c" TEXT,
  "Taxonomy_8__c" TEXT,
  "Taxonomy_9__c" TEXT,
  "Transportation__c" TEXT,
  "Unpublished__c" TEXT,
  "Website__c" TEXT,
  "of_Search_Terms__c" TEXT,
  "Program_Phone_Text__c" TEXT,
  "Target_Long__c" TEXT,
  "Eligibility_Long__c" TEXT,
  "Accessibility_Long__c" TEXT,
  "X211_Agency__c" TEXT,
  "Days_Since_Last_Update__c" TEXT,
  "Program_Taxonomy_Rollup__c" TEXT,
  "attributes" TEXT,
  "keywords" TEXT,
  "AccessibilityPicklist__c" TEXT,
  "Accessibility_Other__c" TEXT,
  "Age_Restriction_Other__c" TEXT,
  "Age_Restrictions__c" TEXT,
  "Business_Hours_Friday__c" TEXT,
  "Business_Hours_Monday__c" TEXT,
  "Business_Hours_Saturday__c" TEXT,
  "Business_Hours_Sunday__c" TEXT,
  "Business_Hours_Thursday__c" TEXT,
  "Business_Hours_Tuesday__c" TEXT,
  "Business_Hours_Wednesday__c" TEXT,
  "Close_Time_Friday__c" TEXT,
  "Close_Time_Monday__c" TEXT,
  "Close_Time_Saturday__c" TEXT,
  "Close_Time_Sunday__c" TEXT,
  "Close_Time_Thursday__c" TEXT,
  "Close_Time_Tuesday__c" TEXT,
  "Close_Time_Wednesday__c" TEXT,
  "CommunitiesServed__c" TEXT,
  "Communities_Served_Other__c" TEXT,
  "DocumentsRequiredPicklist__c" TEXT,
  "Documents_Required_Other__c" TEXT,
  "Gender_Restrictions__c" TEXT,
  "Income_Restrictions_Other__c" TEXT,
  "Income_Restrictions__c" TEXT,
  "Intake_Procedure_Picklist__c" TEXT,
  "Intake_Procedures_Other__c" TEXT,
  "Languages_Consistently_Available__c" TEXT,
  "Medical_Insurance_Types_Accepted__c" TEXT,
  "Medical_Insurance_required__c" TEXT,
  "Open_247__c" TEXT,
  "Open_Time_Friday__c" TEXT,
  "Open_Time_Monday__c" TEXT,
  "Open_Time_Saturday__c" TEXT,
  "Open_Time_Sunday__c" TEXT,
  "Open_Time_Thursday__c" TEXT,
  "Open_Time_Tuesday__c" TEXT,
  "Open_Time_Wednesday__c" TEXT,
  "Program_Special_Notes_Hours__c" TEXT,
  "Race_Restrictions__c" TEXT,
  "Race_or_Ethnicity_restrictions_other__c" TEXT,
  "Site_Address__c" TEXT,
  "Site_Name__c" TEXT,
  "Site_Program_Changes__c" TEXT,
  "Transportation_Description__c" TEXT,
  "Transportation_Services_Offered__c" TEXT,
  "Do_you_accept_collect_calls__c" TEXT,
  "Phone_Description__c" TEXT,
  "Phone_Extension__c" TEXT,
  "Transpose_Completed__c" TEXT,
  "Intake_Procedure_Multiselect__c" TEXT,
  "Emergency_Reference__c" TEXT,
  "Maximum_Age__c" text,
  "Minimum_Age__c" text,
  "AccountName" text
);

CREATE TABLE IF NOT EXISTS "site" (
  "id" TEXT,
  "IsDeleted" TEXT,
  "Name" TEXT,
  "CreatedDate" TEXT,
  "CreatedById" TEXT,
  "LastModifiedDate" TEXT,
  "LastModifiedById" TEXT,
  "SystemModstamp" TEXT,
  "LastActivityDate" TEXT,
  "LastViewedDate" TEXT,
  "LastReferencedDate" TEXT,
  "Account__c" TEXT,
  "Accessibility__c" TEXT,
  "Application_Phone__c" TEXT,
  "Business_Hours_Friday__c" TEXT,
  "Business_Hours_Monday__c" TEXT,
  "Business_Hours_Saturday__c" TEXT,
  "Business_Hours_Sunday__c" TEXT,
  "Business_Hours_Thursday__c" TEXT,
  "Business_Hours_Tuesday__c" TEXT,
  "Business_Hours_Wednesday__c" TEXT,
  "City__c" TEXT,
  "Days_Since_Last_Update__c" TEXT,
  "Email__c" TEXT,
  "English_is_Only_Language_Offered__c" TEXT,
  "Hotline_Phone__c" TEXT,
  "Insurance__c" TEXT,
  "Intake_Hours_Friday__c" TEXT,
  "Intake_Hours_Monday__c" TEXT,
  "Intake_Hours_Saturday__c" TEXT,
  "Intake_Hours_Sunday__c" TEXT,
  "Intake_Hours_Thursday__c" TEXT,
  "Intake_Hours_Tuesday__c" TEXT,
  "Intake_Hours_Wednesday__c" TEXT,
  "Intake_Phone__c" TEXT,
  "Intake_Procedure_Other__c" TEXT,
  "Intake_Procedures__c" TEXT,
  "Island__c" TEXT,
  "Languages__c" TEXT,
  "ProgramPhone__c" TEXT,
  "ServiceDescription__c" TEXT,
  "Specific_Communities__c" TEXT,
  "State__c" TEXT,
  "Status__c" TEXT,
  "Street_Number__c" TEXT,
  "Suite__c" TEXT,
  "Zip_Code__c" TEXT,
  "AKA_Name__c" TEXT,
  "Administrator_Email__c" TEXT,
  "Administrator_Extension__c" TEXT,
  "Administrator_Name__c" TEXT,
  "Administrator_Phone__c" TEXT,
  "Administrator_Title__c" TEXT,
  "Billing_Address_is_Confidential__c" TEXT,
  "Building__c" TEXT,
  "Contact_1_Email__c" TEXT,
  "Contact_1_Extension__c" TEXT,
  "Contact_1_Name__c" TEXT,
  "Contact_1_Phone__c" TEXT,
  "Contact_1_Title__c" TEXT,
  "Contact_2_Email__c" TEXT,
  "Contact_2_Extension__c" TEXT,
  "Contact_2_Name__c" TEXT,
  "Contact_2_Phone__c" TEXT,
  "Contact_2_Title__c" TEXT,
  "Contact_3_Email__c" TEXT,
  "Contact_3_Extension__c" TEXT,
  "Contact_3_Name__c" TEXT,
  "Contact_3_Phone__c" TEXT,
  "Contact_3_Title__c" TEXT,
  "Country__c" TEXT,
  "County__c" TEXT,
  "Created_By_Legacy__c" TEXT,
  "Created_Date_Legacy__c" TEXT,
  "Formal_Update_Date_Legacy__c" TEXT,
  "Full_Site_Name__c" TEXT,
  "Inactivated_Date__c" TEXT,
  "Location_ID__c" TEXT,
  "Location__Latitude__s" TEXT,
  "Location__Longitude__s" TEXT,
  "Location__c" TEXT,
  "Mailing_Address_is_Confidential__c" TEXT,
  "Mailing_City__c" TEXT,
  "Mailing_Country__c" TEXT,
  "Mailing_County__c" TEXT,
  "Mailing_State__c" TEXT,
  "Mailing_Street_Number__c" TEXT,
  "Mailing_Suite__c" TEXT,
  "Mailing_Zip_Code__c" TEXT,
  "Not_in_Directory__c" TEXT,
  "Not_in_Website__c" TEXT,
  "Public_Transit_Access__c" TEXT,
  "Reason_for_Inactivation__c" TEXT,
  "Site_Accessibility__c" TEXT,
  "Site_Hours__c" TEXT,
  "Site_Key__c" TEXT,
  "Site_Phone_10__c" TEXT,
  "Site_Phone_1__c" TEXT,
  "Site_Phone_2__c" TEXT,
  "Site_Phone_3__c" TEXT,
  "Site_Phone_4__c" TEXT,
  "Site_Phone_5__c" TEXT,
  "Site_Phone_6__c" TEXT,
  "Site_Phone_7__c" TEXT,
  "Site_Phone_8__c" TEXT,
  "Site_Phone_9__c" TEXT,
  "Site_Phones__c" TEXT,
  "Travel_Instructions__c" TEXT,
  "Unpublished__c" TEXT,
  "Update_Date_Legacy__c" TEXT,
  "Updated_By_Legacy__c" TEXT,
  "Website__c" TEXT,
  "of_Site_Programs__c" TEXT,
  "X211_Agency__c" TEXT,
  "Mailing_Address__c" TEXT,
  "Street_Address__c" TEXT,
  "attributes" TEXT,
  "Close_Time_Thursday__c" TEXT,
  "Close_Time_Tuesday__c" TEXT,
  "Close_Time_Wednesday__c" TEXT,
  "Mailing_Building__c" TEXT,
  "Open_24_7__c" TEXT,
  "Open_Time_Friday__c" TEXT,
  "Open_Time_Monday__c" TEXT,
  "Open_Time_Saturday__c" TEXT,
  "Open_Time_Sunday__c" TEXT,
  "Open_Time_Thursday__c" TEXT,
  "Open_Time_Tuesday__c" TEXT,
  "Open_Time_Wednesday__c" TEXT,
  "Phone_Description__c" TEXT,
  "Site_Description__c" TEXT,
  "Site_Extension__c" TEXT,
  "Special_Hour__c" TEXT,
  "Accessibility_Other__c" TEXT,
  "Close_Time_Friday__c" TEXT,
  "Close_Time_Monday__c" TEXT,
  "Close_Time_Saturday__c" TEXT,
  "Close_Time_Sunday__c" TEXT,
  "Mailing_Address_Same_as_Physical__c" TEXT
);

CREATE TABLE IF NOT EXISTS "site_program" (
  "id" TEXT,
  "IsDeleted" TEXT,
  "Name" TEXT,
  "CreatedDate" TEXT,
  "CreatedById" TEXT,
  "LastModifiedDate" TEXT,
  "LastModifiedById" TEXT,
  "SystemModstamp" TEXT,
  "LastActivityDate" TEXT,
  "LastViewedDate" TEXT,
  "LastReferencedDate" TEXT,
  "Site__c" TEXT,
  "Program__c" TEXT,
  "Site_Zip_Code__c" TEXT,
  "Accessibility__c" TEXT,
  "Active__c" TEXT,
  "Agency__c" TEXT,
  "Consistent_Availability__c" TEXT,
  "Created_By_Legacy__c" TEXT,
  "Created_Date_Legacy__c" TEXT,
  "Eligibility__c" TEXT,
  "Email__c" TEXT,
  "Fees__c" TEXT,
  "Intake_Procedure__c" TEXT,
  "ML_Priority__c" TEXT,
  "Matchlist_Phone_1__c" TEXT,
  "Matchlist_Phone_2__c" TEXT,
  "Matchlist_Phone_3__c" TEXT,
  "Not_in_Directory__c" TEXT,
  "Not_in_Website__c" TEXT,
  "Note_1__c" TEXT,
  "Note_2__c" TEXT,
  "Program_AKA_Name__c" TEXT,
  "Program_Hours__c" TEXT,
  "Program_Phone__c" TEXT,
  "Program_Service_Area__c" TEXT,
  "Program_Taxonomies__c" TEXT,
  "Program_Website__c" TEXT,
  "Service_Description__c" TEXT,
  "Service_Site_ID__c" TEXT,
  "Site_AKA_Name__c" TEXT,
  "Site_Address__c" TEXT,
  "Site_Island__c" TEXT,
  "Site_Program_Aggregate_Name__c" TEXT,
  "Site_Program_ID__c" TEXT,
  "Transportation__c" TEXT,
  "URL__c" TEXT,
  "Update_Date_Legacy__c" TEXT,
  "Updated_By_Legacy__c" TEXT,
  "Status__c" TEXT,
  "Site_Status__c" TEXT,
  "Program_Status__c" TEXT,
  "Program_Phone_Text__c" TEXT,
  "Location_ID_Site__c" TEXT,
  "Service_ID_Program__c" TEXT,
  "Program_ID__c" TEXT,
  "Site_Phones__c" TEXT,
  "X211_Agency__c" TEXT,
  "Site_Main_Phone__c" TEXT,
  "attributes" TEXT
);

CREATE TABLE IF NOT EXISTS "taxonomy" (
  "id" TEXT,
  "OwnerId" TEXT,
  "IsDeleted" TEXT,
  "Name" TEXT,
  "CreatedDate" TEXT,
  "CreatedById" TEXT,
  "LastModifiedDate" TEXT,
  "LastModifiedById" TEXT,
  "SystemModstamp" TEXT,
  "LastActivityDate" TEXT,
  "LastViewedDate" TEXT,
  "LastReferencedDate" TEXT,
  "AIRS_Problem_Need__c" TEXT,
  "Code__c" TEXT,
  "Definition__c" TEXT,
  "Status__c" TEXT,
  "Term_for_Contact_and_Resources_Module__c" TEXT,
  "Type__c" TEXT,
  "Bibliographic_Reference__c" TEXT,
  "Comments__c" TEXT,
  "Created_Date_Legacy__c" TEXT,
  "Facet__c" TEXT,
  "Keiki_Primary_Category__c" TEXT,
  "Keiki_Secondary_Category__c" TEXT,
  "Last_Modified_Date_Legacy__c" TEXT,
  "Name_255__c" TEXT,
  "Old_Code__c" TEXT,
  "Parent_Taxonomy__c" TEXT,
  "Primary_Category__c" TEXT,
  "Related_Concepts__c" TEXT,
  "Secondary_Category__c" TEXT,
  "Taxonomy_URL__c" TEXT,
  "Use_Reference__c" TEXT,
  "Coronavirus_Primary_Category__c" TEXT,
  "Begins_with_Y__c" TEXT,
  "of_Program_Services__c" TEXT,
  "Coronavirus_Secondary_Taxonomy__c" TEXT,
  "attributes" TEXT,
  "Primary_Category_Search__c" TEXT,
  "Secondary_Category_Search__c" TEXT
);

CREATE TABLE IF NOT EXISTS "suggestion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "text" TEXT NOT NULL,
  "taxonomies" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "user_activity" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "event" TEXT,
  "data" JSON,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trendingRange" TEXT,
  "trendingMinCount" INTEGER,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "trendingMaxShow" INTEGER,
  "manualTrends" INTEGER,
  "trends" JSON,
  "enableTrendingSearches" INTEGER DEFAULT (0),
  "enableRelatedSearches" INTEGER DEFAULT (0),
  "enableTaxonomySearches" INTEGER DEFAULT (0),
  "bannerText" TEXT,
  "bannerLink" TEXT
);

CREATE TABLE IF NOT EXISTS "category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parentId" INTEGER,
  "name" TEXT NOT NULL,
  "icon" TEXT,
  "active" BOOLEAN DEFAULT TRUE,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "params" TEXT
);

CREATE TABLE IF NOT EXISTS "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "lastLogin" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "passwordResetToken" TEXT,
  "passwordResetExp" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "type" TEXT
);

CREATE TABLE IF NOT EXISTS "session" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "data" JSON,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "role" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "permissions" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "user_role" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER,
  "roleId" INTEGER,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "program_service" (
  "id" TEXT,
  "Program__c" TEXT,
  "Taxonomy__c" TEXT,
  "Name" TEXT,
  "IsDeleted" INTEGER,
  "CreatedDate" TEXT,
  "CreatedById" TEXT,
  "LastModifiedDate" TEXT,
  "LastModifiedById" TEXT,
  "SystemModstamp" TEXT
);

CREATE TABLE IF NOT EXISTS "favorite" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "siteProgramId" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "agency_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agencyId" TEXT,
  "language" TEXT,
  "name" TEXT,
  "overview" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "category_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoryId" INTEGER,
  "language" TEXT,
  "name" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "program_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "programId" TEXT,
  "language" TEXT,
  "name" TEXT,
  "ageRestrictions" TEXT,
  "ageRestrictionOther" TEXT,
  "eligibilityLong" TEXT,
  "feesOther" TEXT,
  "fees" TEXT,
  "intakeProcedureMultiselect" TEXT,
  "intakeProceduresOther" TEXT,
  "languagesConsistentlyAvailable" TEXT,
  "languagesText" TEXT,
  "maximumAge" TEXT,
  "minimumAge" TEXT,
  "programSpecialNotesHours" TEXT,
  "serviceDescription" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "site_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "siteId" TEXT,
  "language" TEXT,
  "name" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "taxonomy_translation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "taxonomyId" TEXT,
  "language" TEXT,
  "name" TEXT,
  "definition" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
