ALTER TABLE agency RENAME COLUMN Id TO id;
ALTER TABLE program RENAME COLUMN Id TO id;
ALTER TABLE program_service RENAME COLUMN Id TO id;
ALTER TABLE site RENAME COLUMN Id TO id;
ALTER TABLE site_program RENAME COLUMN Id TO id;
ALTER TABLE taxonomy RENAME COLUMN Id TO id;
