export const accessibility_for_disabilities = {
  id: true,
  location_id: true,
  accessibility: true,
  details: true,
  location: true
}

export const contact = {
  id: true,
  organization_id: true,
  service_id: true,
  service_at_location_id: true,
  name: true,
  title: true,
  department: true,
  email: true,
  organization: true,
  service: true,
  service_at_location: true,
  phone: true
}

export const eligibility = {
  id: true,
  service_id: true,
  eligibility: true,
  service: true
}

export const favorite = {
  id: true,
  userId: true,
  siteProgramId: true,
  updatedAt: true,
  createdAt: true
}

export const funding = {
  id: true,
  organization_id: true,
  service_id: true,
  source: true,
  organization: true,
  service: true
}

export const language = {
  id: true,
  service_id: true,
  location_id: true,
  language: true,
  service: true,
  location: true
}

export const location = {
  id: true,
  organization_id: true,
  name: true,
  alternate_name: true,
  description: true,
  transportation: true,
  latitude: true,
  longitude: true,
  organization: true,
  accessibility_for_disabilities: true,
  physical_address: true,
  postal_address: true,
  language: true,
  phone: true,
  schedule: true,
  service_at_location: true
}

export const metadata = {
  id: true,
  resource_id: true,
  resource_type: true,
  last_action_date: true,
  last_action_type: true,
  field_name: true,
  previous_value: true,
  replacement_value: true,
  updated_by: true
}

export const meta_table_description = {
  id: true,
  name: true,
  language: true,
  character_set: true
}

export const organization = {
  id: true,
  name: true,
  alternate_name: true,
  description: true,
  email: true,
  url: true,
  tax_status: true,
  tax_id: true,
  year_incorporated: true,
  legal_status: true,
  contact: true,
  funding: true,
  location: true,
  phone: true,
  service: true,
  program__old: true
}

export const other_attribute = {
  id: true,
  link_id: true,
  link_type: true,
  taxonomy_term_id: true,
  taxonomy_term: true
}

export const payment_accepted = {
  id: true,
  service_id: true,
  payment: true,
  service: true
}

export const phone = {
  id: true,
  location_id: true,
  service_id: true,
  organization_id: true,
  contact_id: true,
  service_at_location_id: true,
  number: true,
  extension: true,
  type: true,
  language: true,
  description: true,
  organization: true,
  service: true,
  location: true,
  service_at_location: true,
  contact: true
}

export const physical_address = {
  id: true,
  location_id: true,
  attention: true,
  address_1: true,
  city: true,
  region: true,
  state_province: true,
  postal_code: true,
  country: true,
  location: true
}

export const postal_address = {
  id: true,
  location_id: true,
  attention: true,
  address_1: true,
  city: true,
  region: true,
  state_province: true,
  postal_code: true,
  country: true,
  location: true
}

export const program__old = {
  id: true,
  organization_id: true,
  name: true,
  alternate_name: true,
  organization: true,
  service: true
}

export const required_document = {
  id: true,
  service_id: true,
  document: true,
  service: true
}

export const schedule = {
  id: true,
  service_id: true,
  location_id: true,
  service_at_location_id: true,
  valid_from: true,
  valid_to: true,
  dtstart: true,
  until: true,
  wkst: true,
  freq: true,
  interval: true,
  byday: true,
  byweekno: true,
  bymonthday: true,
  byyearday: true,
  description: true,
  service: true,
  location: true,
  service_at_location: true
}

export const search = {
  id: true,
  service_at_location_id: true,
  organization_id: true,
  service_id: true,
  location_id: true,
  organization_name: true,
  service_name: true,
  location_name: true,
  service_description: true,
  service_short_description: true,
  location_latitude: true,
  location_longitude: true,
  physical_address: true,
  physical_address_city: true,
  physical_address_region: true,
  physical_address_state: true,
  physical_address_country: true,
  physical_address_postal_code: true,
  taxonomy_term: true,
  taxonomy_code: true,
  service_area: true,
  phone: true,
  website: true
}

export const service = {
  id: true,
  organization_id: true,
  program_id: true,
  name: true,
  alternate_name: true,
  description: true,
  short_description: true,
  url: true,
  email: true,
  status: true,
  interpretation_services: true,
  application_process: true,
  wait_time: true,
  fees: true,
  accreditations: true,
  licenses: true,
  taxonomy_ids: true,
  emergency_info: true,
  program: true,
  organization: true,
  contact: true,
  eligibility: true,
  funding: true,
  payment_accepted: true,
  phone: true,
  schedule: true,
  service_area: true,
  service_attribute: true,
  service_at_location: true,
  language: true,
  required_document: true
}

export const service_area = {
  id: true,
  service_id: true,
  service_area: true,
  description: true,
  service: true
}

export const service_attribute = {
  id: true,
  service_id: true,
  taxonomy_term_id: true,
  service: true,
  taxonomy_term: true
}

export const service_at_location = {
  id: true,
  service_id: true,
  location_id: true,
  description: true,
  location: true,
  service: true,
  contact: true,
  phone: true,
  schedule: true
}

export const taxonomy_term = {
  id: true,
  term: true,
  description: true,
  parent_id: true,
  taxonomy: true,
  language: true,
  other_attribute: true,
  service_attribute: true
}

export const agency = {
  id: true,
  IsDeleted: true,
  MasterRecordId: true,
  Name: true,
  Type: true,
  ParentId: true,
  BillingStreet: true,
  BillingCity: true,
  BillingState: true,
  BillingPostalCode: true,
  BillingCountry: true,
  BillingLatitude: true,
  BillingLongitude: true,
  BillingGeocodeAccuracy: true,
  BillingAddress: true,
  ShippingStreet: true,
  ShippingCity: true,
  ShippingState: true,
  ShippingPostalCode: true,
  ShippingCountry: true,
  ShippingLatitude: true,
  ShippingLongitude: true,
  ShippingGeocodeAccuracy: true,
  ShippingAddress: true,
  Phone: true,
  Website: true,
  PhotoUrl: true,
  Industry: true,
  NumberOfEmployees: true,
  Description: true,
  OwnerId: true,
  CreatedDate: true,
  CreatedById: true,
  LastModifiedDate: true,
  LastModifiedById: true,
  SystemModstamp: true,
  LastActivityDate: true,
  LastViewedDate: true,
  LastReferencedDate: true,
  IsCustomerPortal: true,
  Jigsaw: true,
  JigsawCompanyId: true,
  AccountSource: true,
  SicDesc: true,
  Agency_Contact_Email__c: true,
  Agency_Contact_Fax__c: true,
  Agency_Contact_Name__c: true,
  Agency_Contact_Phone__c: true,
  Agency_Contact_Primary_Phone__c: true,
  Agency_Contact_Secondary_Phone__c: true,
  Agency_Contact_Title__c: true,
  Email__c: true,
  Employee_Identification_EIN__c: true,
  Fax__c: true,
  Legal_Status_Other__c: true,
  Legal_Status__c: true,
  Mission_Statement__c: true,
  Person_in_Charge_Email__c: true,
  Person_in_Charge_Fax__c: true,
  Person_in_Charge_Name__c: true,
  Person_in_Charge_Primary_Phone__c: true,
  Person_in_Charge_Secondary_Phone__c: true,
  Person_in_Charge_Title__c: true,
  Status__c: true,
  AKA_Name__c: true,
  Admin_Hours__c: true,
  Administrator_Extension__c: true,
  Agency_Accessibility__c: true,
  Agency_Key__c: true,
  Agency_Phone_10__c: true,
  Agency_Phone_1__c: true,
  Agency_Phone_2__c: true,
  Agency_Phone_3__c: true,
  Agency_Phone_4__c: true,
  Agency_Phone_5__c: true,
  Agency_Phone_6__c: true,
  Agency_Phone_7__c: true,
  Agency_Phone_8__c: true,
  Agency_Phone_9__c: true,
  Agency_Phones__c: true,
  Agency_Type__c: true,
  Billing_Address_is_Confidential__c: true,
  Building__c: true,
  Contact_1_Email__c: true,
  Contact_1_Extension__c: true,
  Contact_1_Name__c: true,
  Contact_1_Phone__c: true,
  Contact_1_Title__c: true,
  Contact_2_Email__c: true,
  Contact_2_Extension__c: true,
  Contact_2_Name__c: true,
  Contact_2_Phone__c: true,
  Contact_2_Title__c: true,
  Contact_3_Email__c: true,
  Contact_3_Extension__c: true,
  Contact_3_Name__c: true,
  Contact_3_Phone__c: true,
  Contact_3_Title__c: true,
  County__c: true,
  Created_By_Legacy__c: true,
  Created_Date_Legacy__c: true,
  EB_Send__c: true,
  Facility_Type__c: true,
  Formal_Update_Date_Legacy__c: true,
  IRS_Status__c: true,
  Inactivated_Date__c: true,
  Local_Location__c: true,
  Location_ID__c: true,
  Mailing_Address_is_Confidential__c: true,
  Mailing_County__c: true,
  Not_in_Directory__c: true,
  Not_in_Website__c: true,
  Overview__c: true,
  Public_Transit_Access__c: true,
  Reason_for_Inactivation__c: true,
  Staff_Assigned__c: true,
  Survey_Password__c: true,
  Tax_ID__c: true,
  Unpublished__c: true,
  Update_Date_Legacy__c: true,
  Updated_By_Legacy__c: true,
  Year_Incorporated__c: true,
  Disaster_Preparedness_Services__c: true,
  Suite__c: true,
  Formal_Update_Date__c: true,
  Days_Since_Last_Update__c: true,
  Days_Since_Last_Formal_Update__c: true,
  Agency_Accessibility_Other__c: true,
  Contact_1_Secondary_Phone__c: true,
  Contact_2_Secondary_Phone__c: true,
  Contact_3_Secondary_Phone__c: true,
  How_long_has_Agency_Serviced_in_Hawaii__c: true,
  How_long_has_agency_had_legal_status__c: true,
  IRS_Status_Other__c: true,
  Mailing_Building__c: true,
  Mailing_Suite__c: true,
  Any_Disaster_Preparedness_Services__c: true,
  Describe_Disaster_Preparedness_Services__c: true,
  Mailing_Address_Same_as_Physical__c: true,
  Partner_Agency__c: true
  // Partners_In_Care_PIC_Partner_Agency__c: true,
  // attributes: true
}

export const program = {
  id: true,
  keywords: true,
  OwnerId: true,
  IsDeleted: true,
  Name: true,
  CreatedDate: true,
  CreatedById: true,
  LastModifiedDate: true,
  LastModifiedById: true,
  SystemModstamp: true,
  LastActivityDate: true,
  LastViewedDate: true,
  LastReferencedDate: true,
  Additional_Program_Information__c: true,
  Age_Range_restrictions__c: true,
  Criteria_for_Participation__c: true,
  Description__c: true,
  Family_Composition_restrictions__c: true,
  Fees_Other__c: true,
  Fees__c: true,
  Gender_restrictions_Other__c: true,
  Income_Status_restrictions__c: true,
  Insurance_Other__c: true,
  Medical_Insurance_Plans_Accepted__c: true,
  Other_restrictions__c: true,
  Program_Contact_Email__c: true,
  Program_Contact_Fax__c: true,
  Program_Contact_Name__c: true,
  Program_Contact_Phone__c: true,
  Program_Contact_Title__c: true,
  Race_or_Ethnicity_restrictions__c: true,
  Status__c: true,
  of_Sites__c: true,
  AKA_Name__c: true,
  Accessibility__c: true,
  Account__c: true,
  Additional_Information__c: true,
  Additional_Phones__c: true,
  Eligibility__c: true,
  Fax__c: true,
  Fees_Text__c: true,
  Group_Contact_10__c: true,
  Group_Contact_1__c: true,
  Group_Contact_2__c: true,
  Group_Contact_3__c: true,
  Group_Contact_4__c: true,
  Group_Contact_5__c: true,
  Group_Contact_6__c: true,
  Group_Contact_7__c: true,
  Group_Contact_8__c: true,
  Group_Contact_9__c: true,
  Hours__c: true,
  Insurance__c: true,
  Intake_Person__c: true,
  Intake_Procedure__c: true,
  Languages_Text__c: true,
  Languages__c: true,
  Legacy_Service_Area__c: true,
  Location_ID__c: true,
  Program_Email_Text__c: true,
  Program_Email__c: true,
  Program_Phone__c: true,
  Program_Taxonomies__c: true,
  ServiceArea__c: true,
  Service_Description__c: true,
  Service_Group__c: true,
  Service_ID__c: true,
  Target__c: true,
  Taxonomy_10__c: true,
  Taxonomy_1__c: true,
  Taxonomy_2__c: true,
  Taxonomy_3__c: true,
  Taxonomy_4__c: true,
  Taxonomy_5__c: true,
  Taxonomy_6__c: true,
  Taxonomy_7__c: true,
  Taxonomy_8__c: true,
  Taxonomy_9__c: true,
  Transportation__c: true,
  Unpublished__c: true,
  Website__c: true,
  of_Search_Terms__c: true,
  Program_Phone_Text__c: true,
  Target_Long__c: true,
  Eligibility_Long__c: true,
  Accessibility_Long__c: true,
  X211_Agency__c: true,
  Days_Since_Last_Update__c: true,
  Program_Taxonomy_Rollup__c: true,
  AccessibilityPicklist__c: true,
  Accessibility_Other__c: true,
  Age_Restriction_Other__c: true,
  Age_Restrictions__c: true,
  Business_Hours_Friday__c: true,
  Business_Hours_Monday__c: true,
  Business_Hours_Saturday__c: true,
  Business_Hours_Sunday__c: true,
  Business_Hours_Thursday__c: true,
  Business_Hours_Tuesday__c: true,
  Business_Hours_Wednesday__c: true,
  Close_Time_Friday__c: true,
  Close_Time_Monday__c: true,
  Close_Time_Saturday__c: true,
  Close_Time_Sunday__c: true,
  Close_Time_Thursday__c: true,
  Close_Time_Tuesday__c: true,
  Close_Time_Wednesday__c: true,
  CommunitiesServed__c: true,
  Communities_Served_Other__c: true,
  DocumentsRequiredPicklist__c: true,
  Documents_Required_Other__c: true,
  Gender_Restrictions__c: true,
  Income_Restrictions_Other__c: true,
  Income_Restrictions__c: true,
  Intake_Procedure_Picklist__c: true,
  Intake_Procedures_Other__c: true,
  Languages_Consistently_Available__c: true,
  Medical_Insurance_Types_Accepted__c: true,
  Medical_Insurance_required__c: true,
  Open_247__c: true,
  Open_Time_Friday__c: true,
  Open_Time_Monday__c: true,
  Open_Time_Saturday__c: true,
  Open_Time_Sunday__c: true,
  Open_Time_Thursday__c: true,
  Open_Time_Tuesday__c: true,
  Open_Time_Wednesday__c: true,
  Program_Special_Notes_Hours__c: true,
  Race_Restrictions__c: true,
  Race_or_Ethnicity_restrictions_other__c: true,
  Site_Address__c: true,
  Site_Name__c: true,
  Site_Program_Changes__c: true,
  Transportation_Description__c: true,
  Transportation_Services_Offered__c: true,
  Do_you_accept_collect_calls__c: true,
  Phone_Description__c: true,
  Phone_Extension__c: true,
  Transpose_Completed__c: true,
  Intake_Procedure_Multiselect__c: true,
  Emergency_Reference__c: true,
  Maximum_Age__c: true,
  Minimum_Age__c: true
  // attributes: true
}

export const program_service = {
  id: true,
  Program__c: true,
  Taxonomy__c: true,
  Name: true,
  IsDeleted: true,
  CreatedDate: true,
  CreatedById: true,
  LastModifiedDate: true,
  LastModifiedById: true,
  SystemModstamp: true
}

export const site = {
  id: true,
  IsDeleted: true,
  Name: true,
  CreatedDate: true,
  CreatedById: true,
  LastModifiedDate: true,
  LastModifiedById: true,
  SystemModstamp: true,
  LastActivityDate: true,
  LastViewedDate: true,
  LastReferencedDate: true,
  Account__c: true,
  Accessibility__c: true,
  Application_Phone__c: true,
  Business_Hours_Friday__c: true,
  Business_Hours_Monday__c: true,
  Business_Hours_Saturday__c: true,
  Business_Hours_Sunday__c: true,
  Business_Hours_Thursday__c: true,
  Business_Hours_Tuesday__c: true,
  Business_Hours_Wednesday__c: true,
  City__c: true,
  Days_Since_Last_Update__c: true,
  Email__c: true,
  English_is_Only_Language_Offered__c: true,
  Hotline_Phone__c: true,
  Insurance__c: true,
  Intake_Hours_Friday__c: true,
  Intake_Hours_Monday__c: true,
  Intake_Hours_Saturday__c: true,
  Intake_Hours_Sunday__c: true,
  Intake_Hours_Thursday__c: true,
  Intake_Hours_Tuesday__c: true,
  Intake_Hours_Wednesday__c: true,
  Intake_Phone__c: true,
  Intake_Procedure_Other__c: true,
  Intake_Procedures__c: true,
  Island__c: true,
  Languages__c: true,
  ProgramPhone__c: true,
  ServiceDescription__c: true,
  Specific_Communities__c: true,
  State__c: true,
  Status__c: true,
  Street_Number__c: true,
  Suite__c: true,
  Zip_Code__c: true,
  AKA_Name__c: true,
  Administrator_Email__c: true,
  Administrator_Extension__c: true,
  Administrator_Name__c: true,
  Administrator_Phone__c: true,
  Administrator_Title__c: true,
  Billing_Address_is_Confidential__c: true,
  Building__c: true,
  Contact_1_Email__c: true,
  Contact_1_Extension__c: true,
  Contact_1_Name__c: true,
  Contact_1_Phone__c: true,
  Contact_1_Title__c: true,
  Contact_2_Email__c: true,
  Contact_2_Extension__c: true,
  Contact_2_Name__c: true,
  Contact_2_Phone__c: true,
  Contact_2_Title__c: true,
  Contact_3_Email__c: true,
  Contact_3_Extension__c: true,
  Contact_3_Name__c: true,
  Contact_3_Phone__c: true,
  Contact_3_Title__c: true,
  Country__c: true,
  County__c: true,
  Created_By_Legacy__c: true,
  Created_Date_Legacy__c: true,
  Formal_Update_Date_Legacy__c: true,
  Full_Site_Name__c: true,
  Inactivated_Date__c: true,
  Location_ID__c: true,
  Location__Latitude__s: true,
  Location__Longitude__s: true,
  Location__c: true,
  Mailing_Address_is_Confidential__c: true,
  Mailing_City__c: true,
  Mailing_Country__c: true,
  Mailing_County__c: true,
  Mailing_State__c: true,
  Mailing_Street_Number__c: true,
  Mailing_Suite__c: true,
  Mailing_Zip_Code__c: true,
  Not_in_Directory__c: true,
  Not_in_Website__c: true,
  Public_Transit_Access__c: true,
  Reason_for_Inactivation__c: true,
  Site_Accessibility__c: true,
  Site_Hours__c: true,
  Site_Key__c: true,
  Site_Phone_10__c: true,
  Site_Phone_1__c: true,
  Site_Phone_2__c: true,
  Site_Phone_3__c: true,
  Site_Phone_4__c: true,
  Site_Phone_5__c: true,
  Site_Phone_6__c: true,
  Site_Phone_7__c: true,
  Site_Phone_8__c: true,
  Site_Phone_9__c: true,
  Site_Phones__c: true,
  Travel_Instructions__c: true,
  Unpublished__c: true,
  Update_Date_Legacy__c: true,
  Updated_By_Legacy__c: true,
  Website__c: true,
  of_Site_Programs__c: true,
  X211_Agency__c: true,
  Mailing_Address__c: true,
  Street_Address__c: true,
  Accessibility_Other__c: true,
  Close_Time_Friday__c: true,
  Close_Time_Monday__c: true,
  Close_Time_Saturday__c: true,
  Close_Time_Sunday__c: true,
  Close_Time_Thursday__c: true,
  Close_Time_Tuesday__c: true,
  Close_Time_Wednesday__c: true,
  Mailing_Building__c: true,
  Open_24_7__c: true,
  Open_Time_Friday__c: true,
  Open_Time_Monday__c: true,
  Open_Time_Saturday__c: true,
  Open_Time_Sunday__c: true,
  Open_Time_Thursday__c: true,
  Open_Time_Tuesday__c: true,
  Open_Time_Wednesday__c: true,
  Phone_Description__c: true,
  Site_Description__c: true,
  Site_Extension__c: true,
  Special_Hour__c: true,
  Mailing_Address_Same_as_Physical__c: true
  // attributes: true
}

export const site_program = {
  id: true,
  IsDeleted: true,
  Name: true,
  CreatedDate: true,
  CreatedById: true,
  LastModifiedDate: true,
  LastModifiedById: true,
  SystemModstamp: true,
  LastActivityDate: true,
  LastViewedDate: true,
  LastReferencedDate: true,
  Site__c: true,
  Program__c: true,
  Site_Zip_Code__c: true,
  Accessibility__c: true,
  Active__c: true,
  Agency__c: true,
  Consistent_Availability__c: true,
  Created_By_Legacy__c: true,
  Created_Date_Legacy__c: true,
  Eligibility__c: true,
  Email__c: true,
  Fees__c: true,
  Intake_Procedure__c: true,
  ML_Priority__c: true,
  Matchlist_Phone_1__c: true,
  Matchlist_Phone_2__c: true,
  Matchlist_Phone_3__c: true,
  Not_in_Directory__c: true,
  Not_in_Website__c: true,
  Note_1__c: true,
  Note_2__c: true,
  Program_AKA_Name__c: true,
  Program_Hours__c: true,
  Program_Phone__c: true,
  Program_Service_Area__c: true,
  Program_Taxonomies__c: true,
  Program_Website__c: true,
  Service_Description__c: true,
  Service_Site_ID__c: true,
  Site_AKA_Name__c: true,
  Site_Address__c: true,
  Site_Island__c: true,
  Site_Program_Aggregate_Name__c: true,
  Site_Program_ID__c: true,
  Transportation__c: true,
  URL__c: true,
  Update_Date_Legacy__c: true,
  Updated_By_Legacy__c: true,
  Status__c: true,
  Site_Status__c: true,
  Program_Status__c: true,
  Program_Phone_Text__c: true,
  Location_ID_Site__c: true,
  Service_ID_Program__c: true,
  Program_ID__c: true,
  Site_Phones__c: true,
  X211_Agency__c: true,
  Site_Main_Phone__c: true
  // attributes: true
}

export const taxonomy = {
  id: true,
  OwnerId: true,
  IsDeleted: true,
  Name: true,
  CreatedDate: true,
  CreatedById: true,
  LastModifiedDate: true,
  LastModifiedById: true,
  SystemModstamp: true,
  LastActivityDate: true,
  LastViewedDate: true,
  LastReferencedDate: true,
  AIRS_Problem_Need__c: true,
  Code__c: true,
  Definition__c: true,
  Status__c: true,
  Term_for_Contact_and_Resources_Module__c: true,
  Type__c: true,
  Bibliographic_Reference__c: true,
  Comments__c: true,
  Created_Date_Legacy__c: true,
  Facet__c: true,
  Keiki_Primary_Category__c: true,
  Keiki_Secondary_Category__c: true,
  Last_Modified_Date_Legacy__c: true,
  Name_255__c: true,
  Old_Code__c: true,
  Parent_Taxonomy__c: true,
  Primary_Category__c: true,
  Related_Concepts__c: true,
  Secondary_Category__c: true,
  Taxonomy_URL__c: true,
  Use_Reference__c: true,
  Coronavirus_Primary_Category__c: true,
  Begins_with_Y__c: true,
  of_Program_Services__c: true,
  Coronavirus_Secondary_Taxonomy__c: true,
  Primary_Category_Search__c: true,
  Secondary_Category_Search__c: true
  // attributes: true
}

export const suggestion = {
  id: true,
  text: true,
  taxonomies: true,
  createdAt: true,
  updatedAt: true
}

export const user_activity = {
  id: true,
  userId: true,
  event: true,
  data: true,
  createdAt: true,
  updatedAt: true
}

export const settings = {
  id: true,
  enableTaxonomySearches: true,
  enableTrendingSearches: true,
  enableRelatedSearches: true,
  trendingRange: true,
  trendingMinCount: true,
  trendingMaxShow: true,
  manualTrends: true,
  trends: true,
  bannerText: true,
  bannerLink: true,
  createdAt: true
}

export const category = {
  id: true,
  parentId: true,
  name: true,
  params: true,
  icon: true,
  active: true,
  createdAt: true,
  updatedAt: true
}

export const user = {
  id: true,
  type: true,
  email: true,
  password: true,
  lastLogin: true,
  createdAt: true,
  updatedAt: true
}

export const session = {
  id: true,
  userId: true,
  data: true,
  createdAt: true,
  updatedAt: true
}
